### ISSUE TITLE
decodeMaybe no longer exported.

### ISSUE THREAD

**Issue by cprichmond** [purescript-contrib/purescript-argonaut-codecs#16]
I noticed when you went from v0.6.1 to v1.0.0 of the library the function `decodeMaybe`remains in the  codebase but it is no longer exported. 

https://github.com/purescript-contrib/purescript-argonaut-codecs/blob/master/src/Data/Argonaut/Decode/Class.purs#L143

The `decodeMaybe` function now seems to be orphaned as it's not called anywhere else in the code as far as I can tell. Was this intentional or just an oversight?

Thanks,

Chris.

**Comment by garyb** [comment]
Fixed in #21. Thanks for pointing it out, it was just left in an oversight!
