### ISSUE TITLE
Split instances out for Generic into a standalone library

### ISSUE THREAD

**Issue by garyb** [purescript-contrib/purescript-argonaut-codecs#28]
Since the situation with generics is still up in the air. We can create a generics-rep version too. It'll need newtypes or something, to prevent the instances being orphaned, however (or use of the `gEncodeJson` / `gDecodeJson` directly).

**Comment by dgendill** [comment]
For anyone looking for the old generic `gEncodeJson` and `gDecodeJson` functions, it looks like they are in [purescript-argonaut-generic](https://github.com/purescript-contrib/purescript-argonaut-generic) now.

**Comment by garyb** [comment]
It now has a versioned release too, so closing this :)
