### ISSUE TITLE
easily encode/decode records

### ISSUE THREAD

**Issue by cdepillabout** [purescript-contrib/purescript-argonaut-codecs#5]
Is there a way to easily encode and decode records?

For instance, I have the following type:

```
newtype Register = Register { email :: String
                            , password :: String
                            }
```

I'd like to use purescript-generics for the encoding and decoding like below:

```
derive instance genericRegister :: Generic Register
instance encodeJsonRegister :: EncodeJson Register where
    encodeJson = gEncodeJson
```

But when running the following code:
```
let register = Register { email: "email@email.com", password: "foobar" }
in show $ encodeJson res
```
I get the following output: `{"values":[{"password":"foobar","email":"email@email.com"}],"tag":"Register"}`
I was expecting the output to look like this: `{"password":"foobar","email":"email@email.com"}`

I tried to change the EncodeJson instance like the following:
```
instance encodeJsonRegister :: EncodeJson Register where
    encodeJson (Register reg) = gEncodeJson reg
```
But that just gave me the following compiler error:
```
Error found:
Error in value declaration encodeJsonRegister:
Error at /opt/src/src/Main.purs line 44, column 1 - line 46, column 1:
Error in module Main:
No instance found for

  Data.Generic.Generic { password :: String
                       , email :: String
                       }
```

The error makes sense, but I was hoping it would be easier to define `encodeJson` for records.  Is there an easy way?  I don't want to have to write out something like this for every type:
```
  instance encodeJsonRegister :: EncodeJson Register where
    encodeJson (Register reg)
      =  "email" := reg.email
      ~> "password" := reg.password
      ~> jsonEmptyObject
```

Maybe I've just been spoiled by `aeson` :-(

**Comment by zudov** [comment]
Perhaps we could add a special case in `gEncodeJSON`/`gDecodeJSON` for ADTs with single constructors and single argument, so that they would be simply encoding/decoding that argument.

How does that sound?

**Comment by zudov** [comment]
I wonder if compiler could automatically derive Generic for records which only contain Generic keys, this would be much nicer and then what you tried would just work.

**Comment by zudov** [comment]
At the moment `gEncodeJson`/`gDecodeJson` is just a direct and very obvious mapping between `GenericSpine` and `JSON`.

To be honest, I didn't really intend it to be used as something "human consumable", the primary target are the cases where you just need an isomorphic serialization/deserialization (like if you want to save something to localstorage).

Making an exception for newtypes would break that property, and `gDecodeJSON` would become ambiguous.

**Comment by cdepillabout** [comment]
I guess I'll just write my own version of `gEncodeJSON`.

It would be nice to have a function similar to [`deriveJSON`](https://hackage.haskell.org/package/aeson/docs/Data-Aeson-TH.html#v:deriveJSON) that could take options on how to do the encoding/decoding.

Then you would be able to write something like this:

```
myOpts :: ArgonautCodecOptions
myOpts ...

derive instance genericRegister :: Generic Register
instance encodeJsonRegister :: EncodeJson Register where
    encodeJson = encodeJsonWithOptions myOpts
instance decodeJsonRegister :: DecodeJson Register where
    decodeJson = decodeJsonWithOptions myOpts
```

**Comment by eskimor** [comment]
I am currently working on genericEncodeJson which takes options like Haskell's aeson does. I plan to file a pull request later in the evening. Unwrapping newtype like data is currently not supported, but it should be easy to add.

**Comment by eskimor** [comment]
Btw.: if all you really want is a record, it works already, just change your definition to:
type Register =  { email :: String
                            , password :: String
                            }

**Comment by eskimor** [comment]
@cdepillabout would changing newtype to type fix your problem? I personally am a bit hesitant to adding even more options, when they are not really needed. Even Aeson has unwrapUnaryRecords switched off by default.

If you are fine with changing newtype to type, I would suggest to close this issue and only implement "unwrapUnaryRecords" once it is really needed for some reason.

**Comment by eskimor** [comment]
Ok, after further investigation, this modified example from @cdepillabout does not work:
```
newtype Register = Register RegisterImpl

type RegisterImpl = { email :: String
                    , password :: String
                    }

-- instance genericRegisterImpl :: Generic RegisterImpl
instance encodeJsonRegister :: EncodeJson Register where
    encodeJson (Register reg) = gEncodeJson reg
```
Nor does it work, if you add:
```
instance genericRegisterImpl :: Generic RegisterImpl
```
or
```
instance genericRegisterImpl :: Generic Object ( email :: String , password :: String )
```

this seems to be related to:

https://github.com/purescript/purescript/issues/1822

if https://github.com/purescript/purescript/issues/1822 does not get resolved somehow, maybe I should implement "unwrapUnaryRecords" as a workaround. 

Should I file a PR documenting that a newtype wrapper around records is needed, in order to be usable with argonaut encoding/decoding?

**Comment by eskimor** [comment]
unwrapUnaryRecords implemented [here](https://github.com/eskimor/purescript-argonaut-generic-codecs).

**Comment by texastoland** [comment]
Can this be closed? It doesn't serve the use case of a type having all non-`Generic` `*code`-able fields.

**Comment by cdepillabout** [comment]
Yes, I believe this can be considered fixed with the `unwrapUnaryRecords` option.
