### ISSUE TITLE
Wrong type shown in docs

### ISSUE THREAD

**Issue by xWafl** [purescript-contrib/purescript-argonaut-codecs#87]
**Describe the bug**
In Pursuit, the type of `decodeJson` (as listed on the `DecodeJson` typecclass) is shown as `Json -> Either String a`. However, it is `Json -> Either JsonDecodeError a` in the code.

**Expected behavior**
An updated documentation, this is the only error that I have come across thus far, however, there could be other errors.

**Comment by thomashoneyman** [comment]
Ah, you're right, this uses the wrong type:

https://github.com/purescript-contrib/purescript-argonaut-codecs/blob/main/docs/README.md#automatic-encoding-with-encodejson-and-encodejson

It looks correct elsewhere in the documentation so it should just be that line that needs to be updated. Would you like to patch it?
